### ISSUE TITLE
子副图全部显示错误指标

### ISSUE THREAD

**Issue by leolianggit** [wangyiqian/StockChart#10]
更新版本号，子副图全部显示错误指标
![12](https://user-images.githubusercontent.com/49511566/224276824-975c0bdf-9b48-483b-9351-b14e898eda1a.png)

**Comment by wangyiqian** [comment]
你好 这个截图是直接运行我的示例工程跑的么 有改过吗 因为我这运行是正常的

**Comment by wangyiqian** [comment]
还有问题欢迎反馈，没问题先关掉了

**Comment by leolianggit** [comment]
上周五更新的有问题，今天更新的可以正常展示，我这边没有修改过代码，直接clone下来运行的

**Comment by wangyiqian** [comment]
> 上周五更新的有问题，今天更新的可以正常展示，我这边没有修改过代码，直接clone下来运行的

嗯嗯 最近修改了下示例的指标子图高度 感谢反馈
