### ISSUE TITLE
数据量较少时,蜡烛图等形状过大

### ISSUE THREAD

**Issue by wisdomcai** [wangyiqian/StockChart#11]
如题,可否给个参数设置下最大宽度,或者告知下在什么地方调整一下宽度的设置,谢谢

**Comment by wangyiqian** [comment]
> 如题,可否给个参数设置下最大宽度,或者告知下在什么地方调整一下宽度的设置,谢谢

KChartConfig配置的barSpaceRatio通过比例来控制柱子宽度
