### ISSUE TITLE
分时以及五日问题

### ISSUE THREAD

**Issue by Q2453267246** [wangyiqian/StockChart#16]
我的分时在某些时间点是没有数据的，加入在10:30 - 10:45 没有数据，那么在收盘的时候，分时数据就会有问题，横坐标是对不上的，想知道这部分需要在哪里进行修改。

**Comment by wangyiqian** [comment]
10:30-10:45这段时间的数据点用空点填充，KEntity的flag设置为FLAG_EMPTY就是空点，或直接用EmptyKEntity
