### ISSUE TITLE
VolumeChart增加MA5和MA10，应该怎么处理

### ISSUE THREAD

**Issue by vicliang1990** [wangyiqian/StockChart#17]
需要在VolumeChart增加MA5和MA10均线，应该怎么绘制

**Comment by wangyiqian** [comment]
> 需要在VolumeChart增加MA5和MA10均线，应该怎么绘制

需要通过自定义子图的方式实现 默认的配置没有这种

**Comment by vicliang1990** [comment]
好的，已经添加成功了
