### ISSUE TITLE
加载更多数据问题

### ISSUE THREAD

**Issue by 123abcwqaq-cj** [wangyiqian/StockChart#18]
每次加载200条股票， 但是在画MA线的时候，当滑倒最左边的时候，线是断的，需要再向前加载200根才能连起来，我该怎么处理这种在加载边界index线不连接的情况。

**Comment by wangyiqian** [comment]
> 每次加载200条股票， 但是在画MA线的时候，当滑倒最左边的时候，线是断的，需要再向前加载200根才能连起来，我该怎么处理这种在加载边界index线不连接的情况。

嗯 因为MA计算的时候需要知道前面的N个点的数据 滑到最左边新数据还未加载出来的时候 由于数据点不够此时没法计算出前几个数据点的MA结果 。 如果你想要连续，那么可以提前加载数据而不是用现在的加载数据时机，比如自定义子图监听绘制时的最左边的那个数据点的下标，如果发现滑动到了还剩1/3数据时就提前开始加载下一页数据。

**Comment by 123abcwqaq-cj** [comment]
但是加载更多不是写在StockChart的MatrixHelper里面的吗？这部分子图好像重写不了啊。

**Comment by wangyiqian** [comment]
> 但是加载更多不是写在StockChart的MatrixHelper里面的吗？这部分子图好像重写不了啊。

原加载回调不变，改用自定义子图里你自己逻辑加的回调
