### ISSUE TITLE
StockChart在RecyclerView下渲染出现异常

### ISSUE THREAD

**Issue by NicoToast** [wangyiqian/StockChart#2]
问题：StockChart在RecyclerView会出现无法缩放、K线图变小问题
复现步骤：StockChart所在的ViewHolder划出屏幕后再次划入屏幕。
复现代码：https://github.com/NicoToast/StockChart/tree/feature/rv_test 的 sample4

**Comment by wangyiqian** [comment]
您好，根据您写的demo，由于RecyclerView的回收机制，您不应在StockChartViewHolder的init中设置itemView.stock_chart，应该都写到onBind中，参考伪代码：
```
class StockChartViewHolder(...){

    fun onBind(model: StockModel) {
        val mStockChartConfig = StockChartConfig()
        val mKChartConfig = KChartConfig()
        val mTimeBarConfig = TimeBarConfig()
        itemView.stock_chart.apply {
            setConfig(mStockChartConfig)
            mStockChartConfig.apply {
                ...
            }
            mKChartConfig.apply {
                ...
            }
            mTimeBarConfig.apply {
                ...
            }
            mStockChartConfig.setKEntities(
                ...
            )
            notifyChanged()
        }
    }
}
```

**Comment by NicoToast** [comment]
感谢回复，已经解决，谢谢

**Comment by same4869** [comment]
目前在rv中，只要划出去一点点（也就是刚好被划出去），然后再划回来图表数据就乱了，此时感觉还没走到onBind中，有没有什么排查思路，谢谢

**Comment by wangyiqian** [comment]
> 

麻烦提供一个复现问题的示例，我帮你看下。

**Comment by wangyiqian** [comment]
> 目前在rv中，只要划出去一点点（也就是刚好被划出去），然后再划回来图表数据就乱了，此时感觉还没走到onBind中，有没有什么排查思路，谢谢
麻烦提供一个复现问题的示例，我帮你看下。

**Comment by wangyiqian** [comment]
> 目前在rv中，只要划出去一点点（也就是刚好被划出去），然后再划回来图表数据就乱了，此时感觉还没走到onBind中，有没有什么排查思路，谢谢

麻烦提供一个复现问题的示例，我帮你看下。

**Comment by same4869** [comment]
按照上面的思路差不多能解决，我自己再研究下先，感谢回复
