### ISSUE TITLE
使用中出现的问题及建议

### ISSUE THREAD

**Issue by chenjieneng** [wangyiqian/StockChart#20]
1. KChart.kt 文件中的 drawHighestAndLowestLabel(canvas: Canvas) 方法 里面的 getKEntities().filterIndexed { kEntityIdx, kEntity ->
                    kEntityIdx in leftIdx..rightIdx && !kEntity.containFlag(
                        FLAG_EMPTY
                    )
                }
                    .map { it.getHighPrice() }.max() 有时候会出现为空的问题 ; 根据提示可以为: getKEntities().filterIndexed { kEntityIdx, kEntity ->
                    kEntityIdx in leftIdx..rightIdx && !kEntity.containFlag(
                        FLAG_EMPTY
                    )
                }.maxOfOrNull { it.getHighPrice() }
2.  MACalculator.kt 等算法存在的问题 , 例如当没有设置 MA 天数时(如: const val MA = "" )  calculate 方法异常, 没有 param 的非空判断
3. 使用中的建议: 长按的手势响应,可否切换到点击事件; 可否增加实时更新的效果,就像长按那样有个对纵坐标的提示

**Comment by wangyiqian** [comment]
> 

感谢反馈，第一、二点已经进行了优化并发布。第三点个性化需求需要自己通过自定义子图的方式实现自己的逻辑。

**Comment by chenjieneng** [comment]
好的,谢谢
