### ISSUE TITLE
在RecyclerView上下滑动后，部分item的山脉图（我使用的图表类型）出现了图表翻转，minY，maxY区间也翻转了

### ISSUE THREAD

**Issue by CMWW** [wangyiqian/StockChart#22]

**Comment by CMWW** [comment]
![Uploading screenshot-20231102-153806.png…]()

**Comment by CMWW** [comment]
[https://yunwoke.oss-cn-hangzhou.aliyuncs.com/download/screenshot-20231102-153806.png](url)

**Comment by CMWW** [comment]
https://yunwoke.oss-cn-hangzhou.aliyuncs.com/download/screenshot-20231102-153806.png

**Comment by wangyiqian** [comment]
> https://yunwoke.oss-cn-hangzhou.aliyuncs.com/download/screenshot-20231102-153806.png

参考 #2 看是否同一个问题，还是解决不了麻烦给个必现的demo我帮你看下

**Comment by CMWW** [comment]
https://yunwoke.oss-cn-hangzhou.aliyuncs.com/download/StockChart.zip       这是demo

**Comment by wangyiqian** [comment]
> https://yunwoke.oss-cn-hangzhou.aliyuncs.com/download/StockChart.zip 这是demo

你好 该问题已在最新1.1.15版本中修复 感谢反馈
