### ISSUE TITLE
想把长按时显示信息改为按下就显示信息如何改呢?

### ISSUE THREAD

**Issue by roybill** [wangyiqian/StockChart#24]

**Comment by wangyiqian** [comment]
你要，可以通过自定义子图实现，重写父类BaseChildChart的onTap，绘制代码写这个方法里

**Comment by wangyiqian** [comment]
> _No description provided._

你好，可以通过自定义子图实现，重写父类BaseChildChart的onTap，绘制代码写这个方法里

**Comment by roybill** [comment]
> > _No description provided._
> 
> 你好，可以通过自定义子图实现，重写父类BaseChildChart的onTap，绘制代码写这个方法里

作者如果有空,能否更新一个版本,暴露一个API直接去控制长按或短按显示信息呢?我对比了一下其他的K线开源库,那些的做法都是单击即可显示

**Comment by roybill** [comment]
> > _No description provided._
> 
> 你好，可以通过自定义子图实现，重写父类BaseChildChart的onTap，绘制代码写这个方法里

如果把顶部信息做成弹框显示就更好了

**Comment by chensj1992** [comment]
请问，目标的显示区域蜡烛图30个，只显示3条（需要按占比显示），怎么实现？
![000](https://github.com/wangyiqian/StockChart/assets/56785481/1ffebe8e-6ffd-45cb-9cfe-5531117fcb9c)
![4e784e1d7d12eb8eb3afd5df22f460b](https://github.com/wangyiqian/StockChart/assets/56785481/e42b8c43-3712-4a27-8733-2978fd44db62)

**Comment by wangyiqian** [comment]
顶部信息做成弹窗也通过自定义子图实现
