### ISSUE TITLE
请问，显示区域蜡烛图30个，只显示3条（需要按占比显示），这个需求要怎么实现呢？

### ISSUE THREAD

**Issue by chensj1992** [wangyiqian/StockChart#25]
![000](https://github.com/wangyiqian/StockChart/assets/56785481/37b4f02c-354e-4130-86f4-27b500471a9f)
![4e784e1d7d12eb8eb3afd5df22f460b](https://github.com/wangyiqian/StockChart/assets/56785481/9c508928-6d9a-4097-b7b2-288f1ecf3caa)

**Comment by zmc969213509** [comment]
添加27个空数据即可  示例中 年初至今有相关代码

**Comment by chensj1992** [comment]
好的 谢谢

**Comment by chensj1992** [comment]
好的 谢谢

**Comment by Q2453267246** [comment]
添加空数据后，如果有缩放需求，样式可能会出错，这个有解决方法吗？

**Comment by wangyiqian** [comment]
> 添加空数据后，如果有缩放需求，样式可能会出错，这个有解决方法吗？

你好，麻烦把缩放样式出错录个屏，发到我邮箱wangyiqian9891@gmail.com，我看下问题
