### ISSUE TITLE
实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？谢谢

### ISSUE THREAD

**Issue by ZuJunJun** [wangyiqian/StockChart#4]
实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？

**Comment by wangyiqian** [comment]
你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例

**Comment by wangyiqian** [comment]
> 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？

你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例

**Comment by ZuJunJun** [comment]
> > 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？
> 
> 你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例

请问demo上的小标签怎么弄的？我看了代码，应该不是自定义的吧？就是下面这个图上圈出来的这个，麻烦指点一下，谢谢
![微信截图_20220216151046](https://user-images.githubusercontent.com/21032325/154214231-bc859d34-4acb-4977-80aa-d9bec086de7c.png)

**Comment by wangyiqian** [comment]
> > > 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？
> > 
> > 
> > 你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例
> 
> 请问demo上的小标签怎么弄的？我看了代码，应该不是自定义的吧？就是下面这个图上圈出来的这个，麻烦指点一下，谢谢 ![微信截图_20220216151046](https://user-images.githubusercontent.com/21032325/154214231-bc859d34-4acb-4977-80aa-d9bec086de7c.png)

这是最高最低价标签配置 默认蜡烛图是与配置的 如果修改配置参考：
`        val kChartConfig = KChartConfig()
        kChartConfig.kChartType = KChartConfig.KChartType.CANDLE(highestAndLowestLabelConfig = KChartConfig.HighestAndLowestLabelConfig(
            { "${NumberFormatUtil.formatPrice(it)}" },
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_COLOR,
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_TEXT_SIZE,
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_STROKE_WIDTH,
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_LENGTH
        ))
`

**Comment by wangyiqian** [comment]
> > > 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？
> > 
> > 
> > 你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例
> 
> 请问demo上的小标签怎么弄的？我看了代码，应该不是自定义的吧？就是下面这个图上圈出来的这个，麻烦指点一下，谢谢 ![微信截图_20220216151046](https://user-images.githubusercontent.com/21032325/154214231-bc859d34-4acb-4977-80aa-d9bec086de7c.png)

这是最高最低价标签配置 默认蜡烛图是自带这个配置的 如果修改配置参考：
```
        val kChartConfig = KChartConfig()
        kChartConfig.kChartType = KChartConfig.KChartType.CANDLE(highestAndLowestLabelConfig = KChartConfig.HighestAndLowestLabelConfig(
            { "${NumberFormatUtil.formatPrice(it)}" },
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_COLOR,
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_TEXT_SIZE,
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_STROKE_WIDTH,
            DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_LENGTH
        ))
```

**Comment by ZuJunJun** [comment]
> > > > 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？
> > > 
> > > 
> > > 你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例
> > 
> > 
> > 请问demo上的小标签怎么弄的？我看了代码，应该不是自定义的吧？就是下面这个图上圈出来的这个，麻烦指点一下，谢谢 ![微信截图_20220216151046](https://user-images.githubusercontent.com/21032325/154214231-bc859d34-4acb-4977-80aa-d9bec086de7c.png)
> 
> 这是最高最低价标签配置 默认蜡烛图是自带这个配置的 如果修改配置参考：
> 
> ```
>         val kChartConfig = KChartConfig()
>         kChartConfig.kChartType = KChartConfig.KChartType.CANDLE(highestAndLowestLabelConfig = KChartConfig.HighestAndLowestLabelConfig(
>             { "${NumberFormatUtil.formatPrice(it)}" },
>             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_COLOR,
>             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_TEXT_SIZE,
>             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_STROKE_WIDTH,
>             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_LENGTH
>         ))
> ```

好的，我看一下，谢谢

**Comment by ZuJunJun** [comment]
> > > > > 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？
> > > > 
> > > > 
> > > > 你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例
> > > 
> > > 
> > > 请问demo上的小标签怎么弄的？我看了代码，应该不是自定义的吧？就是下面这个图上圈出来的这个，麻烦指点一下，谢谢 ![微信截图_20220216151046](https://user-images.githubusercontent.com/21032325/154214231-bc859d34-4acb-4977-80aa-d9bec086de7c.png)
> > 
> > 
> > 这是最高最低价标签配置 默认蜡烛图是自带这个配置的 如果修改配置参考：
> > ```
> >         val kChartConfig = KChartConfig()
> >         kChartConfig.kChartType = KChartConfig.KChartType.CANDLE(highestAndLowestLabelConfig = KChartConfig.HighestAndLowestLabelConfig(
> >             { "${NumberFormatUtil.formatPrice(it)}" },
> >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_COLOR,
> >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_TEXT_SIZE,
> >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_STROKE_WIDTH,
> >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_LENGTH
> >         ))
> > ```
> 
> 好的，我看一下，谢谢

另外请问一下是否可以修改实心蜡烛图的宽度，现在是通过setBarSpaceRatio修改的，谢谢

**Comment by wangyiqian** [comment]
> 

自带子图的柱子宽度只支持setBarSpaceRatio来修改宽度

**Comment by wangyiqian** [comment]
> > > > > > 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？
> > > > > 
> > > > > 
> > > > > 你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例
> > > > 
> > > > 
> > > > 请问demo上的小标签怎么弄的？我看了代码，应该不是自定义的吧？就是下面这个图上圈出来的这个，麻烦指点一下，谢谢 ![微信截图_20220216151046](https://user-images.githubusercontent.com/21032325/154214231-bc859d34-4acb-4977-80aa-d9bec086de7c.png)
> > > 
> > > 
> > > 这是最高最低价标签配置 默认蜡烛图是自带这个配置的 如果修改配置参考：
> > > ```
> > >         val kChartConfig = KChartConfig()
> > >         kChartConfig.kChartType = KChartConfig.KChartType.CANDLE(highestAndLowestLabelConfig = KChartConfig.HighestAndLowestLabelConfig(
> > >             { "${NumberFormatUtil.formatPrice(it)}" },
> > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_COLOR,
> > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_TEXT_SIZE,
> > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_STROKE_WIDTH,
> > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_LENGTH
> > >         ))
> > > ```
> > 
> > 
> > 好的，我看一下，谢谢
> 
> 另外请问一下是否可以修改实心蜡烛图的宽度，现在是通过setBarSpaceRatio修改的，谢谢

自带子图的柱子宽度只支持setBarSpaceRatio来修改宽度

**Comment by ZuJunJun** [comment]
> > > > > > > 实心蜡烛K线图，蜡烛上的小标签出不来，请问在哪配置？
> > > > > > 
> > > > > > 
> > > > > > 你好，自带的子图蜡烛上没有小标签，当自带子图满足不了您的需求时，可以尝试自定义子图功能，参考下文档和示例
> > > > > 
> > > > > 
> > > > > 请问demo上的小标签怎么弄的？我看了代码，应该不是自定义的吧？就是下面这个图上圈出来的这个，麻烦指点一下，谢谢 ![微信截图_20220216151046](https://user-images.githubusercontent.com/21032325/154214231-bc859d34-4acb-4977-80aa-d9bec086de7c.png)
> > > > 
> > > > 
> > > > 这是最高最低价标签配置 默认蜡烛图是自带这个配置的 如果修改配置参考：
> > > > ```
> > > >         val kChartConfig = KChartConfig()
> > > >         kChartConfig.kChartType = KChartConfig.KChartType.CANDLE(highestAndLowestLabelConfig = KChartConfig.HighestAndLowestLabelConfig(
> > > >             { "${NumberFormatUtil.formatPrice(it)}" },
> > > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_COLOR,
> > > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_TEXT_SIZE,
> > > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_STROKE_WIDTH,
> > > >             DEFAULT_K_CHART_HIGHEST_AND_LOWEST_LABEL_LINE_LENGTH
> > > >         ))
> > > > ```
> > > 
> > > 
> > > 好的，我看一下，谢谢
> > 
> > 
> > 另外请问一下是否可以修改实心蜡烛图的宽度，现在是通过setBarSpaceRatio修改的，谢谢
> 
> 自带子图的柱子宽度只支持setBarSpaceRatio来修改宽度

OK，谢谢
