### ISSUE TITLE
您好，新的问题请教

### ISSUE THREAD

**Issue by ZuJunJun** [wangyiqian/StockChart#5]
https://user-images.githubusercontent.com/21032325/154453985-d513c17b-fc44-4cce-8780-17d56370c4fb.mp4

您好，请问一下现有功能是否支持如视频内右侧跟随close价格浮动的蓝色小标签，以及K线视图能否不与右侧标签重叠。谢谢

**Comment by wangyiqian** [comment]
> 06efe72db99b5439ff573a4fd78eb6f8.mp4 
> 您好，请问一下现有功能是否支持如视频内右侧跟随close价格浮动的蓝色小标签，以及K线视图能否不与右侧标签重叠。谢谢

1. 蓝色小标签内置子图没有，这些个性化UI都可以通过自定义子图自己实现绘制
2. 初始K线显示若想在右侧保持一定空白区间可以在K线数据点的最右边追加一些空点，KEntity的flag标记为FLAG_EMPTY表示一个空点
