### ISSUE TITLE
您好，默认的图有点小，请问有方法可以设置默认的比例大一点吗？谢谢

### ISSUE THREAD

**Issue by ZuJunJun** [wangyiqian/StockChart#6]
您好，默认的图有点小，请问有方法可以设置默认的比例大一点吗？谢谢

**Comment by wangyiqian** [comment]
> 您好，默认的图有点小，请问有方法可以设置默认的比例大一点吗？谢谢

通过控制初始K线点数量就可以，如下减少pageSize数量即可
```
// 初始显示最后50条数据
val pageSize = 50

// 设置加载到的数据
stockChartConfig.setKEntities(
    kEntities,
    showStartIndex = kEntities.size - pageSize,
    showEndIndex = kEntities.size - 1
)
```

**Comment by ZuJunJun** [comment]
> > 您好，默认的图有点小，请问有方法可以设置默认的比例大一点吗？谢谢
> 
> 通过控制初始K线点数量就可以，如下减少pageSize数量即可
> 
> ```
> // 初始显示最后50条数据
> val pageSize = 50
> 
> // 设置加载到的数据
> stockChartConfig.setKEntities(
>     kEntities,
>     showStartIndex = kEntities.size - pageSize,
>     showEndIndex = kEntities.size - 1
> )
> ```

h好的，我尝试一下，谢谢
