### ISSUE TITLE
您好，当小数点之后的位数比较多七八位的时候绘图有问题，请问一下怎么解决？谢谢

### ISSUE THREAD

**Issue by ZuJunJun** [wangyiqian/StockChart#7]
![56e33ea200249081a151da697da6e2b](https://user-images.githubusercontent.com/21032325/155320385-ca646a03-8ecd-46b6-8aa4-27773062796a.jpg)

**Comment by ZuJunJun** [comment]
小数类型比如0.00002715这种

**Comment by ZuJunJun** [comment]
好像是库里float支持的小数位数不够

**Comment by ZuJunJun** [comment]
好像修改一下这个就可以了。if (abs(yMin - yMax) > 0.00000001) {

**Comment by wangyiqian** [comment]
> 好像修改一下这个就可以了。if (abs(yMin - yMax) > 0.00000001) {

是的 针对这个问题 我在最新版本1.0.21我加了配置项 用法如下：
```
val stockChartConfig = StockChartConfig()
stockChartConfig.valueTendToZero = 0.00000001f
```

**Comment by ZuJunJun** [comment]
> > 好像修改一下这个就可以了。if (abs(yMin - yMax) > 0.00000001) {
> 
> 是的 针对这个问题 我在最新版本1.0.21我加了配置项 用法如下：
> 
> ```
> val stockChartConfig = StockChartConfig()
> stockChartConfig.valueTendToZero = 0.00000001f
> ```

好的，我直接添加的module，改了些源码，您确定修改是这个问题就行，那我就也修改这里了，谢谢
